### PR TITLE
Mptcp reset option

### PR DESCRIPTION
**Pull request by fw-strlen**
This extends packetdrill with support for the mptcp reset option. Also adds test cases for the reset option and updates affected mptcp test cases to expect presence of the mptcp reset option.  This needs mptcp-next kernel with mptcp reset option support.

### CODE REVIEW

**Comment by dcaratti** [comment]
patch LGTM. @matttbe,  we might merge this PR first, and then fix `mp_reset_multi_v4.pkt` to cope with the missing "echoed" `ADD_ADDR`. WDYT?

**Comment by matttbe** [comment]
> @matttbe, we might merge this PR first, and then fix mp_reset_multi_v4.pkt to cope with the missing "echoed" ADD_ADDR. WDYT?

@dcaratti Sounds good to me!
But be careful that for this PR, we need to wait to have the kernel patch in our tree: https://patchwork.ozlabs.org/project/mptcp/patch/20210222124940.23943-1-fw@strlen.de/ (waiting for review)

Note that if you want, we can also rebase this PR 45 on top of 46. You should also have the right to push to the mptcp_reset_option branch on fw-strlen/packetdrill repo ;-)

**Comment by matttbe** [comment]
Hi Florian,

Thank you for these patches!

I hope you don't mind, I just modified the scripts you added to follow the structures of the others: https://github.com/multipath-tcp/packetdrill/compare/26aadab2df2b1ed824f5c0001305158e1c83e069..0d2e6fd606c38c013ffe8bcb28bd4a339611802a

For me, it helps to read and review them but we can of course change that if it is a problem.
(e.g. when we have to deal with multiple src/dst addresses, it starts to be too wide maybe)

**Review by matttbe — APPROVED** [review]
Hi Florian,

Thank you for the patches!

I just did another modification to add `--tolerance_usec` option missing in one test.
https://github.com/multipath-tcp/packetdrill/compare/0d2e6fd606c38c013ffe8bcb28bd4a339611802a..f24a51364f9c1f0918dde8c050ad9087dbe6e279

The rest looks good to me!

@dcaratti is it also OK for you? Especially the modification of the parser and others :)

Cheers,
Matt

**Comment by matttbe** [comment]
@dcaratti arf, sorry, I forgot you already said "LGTM" :)

All good then, just have to wait for the kernel patches to be merged first then :)

**Pull request merged**
