### PR TITLE
 mptcp: global: slow down connections

### PR DESCRIPTION
**Pull request by matttbe**
Many of the recent instabilities have been due to the TCP stack being too aggressive to retransmit packets. Adding some delays in the injected packets at the beginning of the connections often help to avoid too aggressive retransmissions.

In this commit, instead of looking at errors reported by the CI, the different files have been manually analysed to add some delays were it was missing.

While at it, unnecessary delays added to the packets generated by the kernel have been removed: if there is no reason to have a delay, no need to add one and expect that the tolerance will save us.

On top of that, some other fixes have been added.

### CODE REVIEW

**Comment by matttbe** [comment]
Just added two extra fixes: to fix issues I saw when running these tests in a loop (100 iterations, 8 in parallel with 2 CPUs cores: so more stressed than usual)

**Comment by matttbe** [comment]
@dcaratti (just to avoid a deadlock, not to push, it is not urgent :) ) do you need a hand to review this PR?

There are a lot of files being modified here, mostly due to the first commit, but most modifications are the same. If it helps, we can also merge, and check if there are new instabilities reported by the CI. Except with [mptcp: join: inject ACK, then ADD_ADDR](https://github.com/multipath-tcp/packetdrill/pull/148/commits/d1c5c906a3b692aad2162519bc6e820f61188feb), I only changed the delays. I then don't think I changed the behaviour, not changed what was being validated.

**Comment by dcaratti** [comment]
LGTM!

**Comment by matttbe** [comment]
thank you! :-)

I can look at backporting all that now! (EDIT: done)

**Pull request merged**
